// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {agent} from '../models';
import {filetree} from '../models';

export function AddProject(arg1:string,arg2:string):Promise<project.Project>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateTerminal(arg1:string,arg2:number,arg3:number):Promise<string>;

export function DeleteProject(arg1:number):Promise<void>;

export function GetAllLayouts():Promise<Record<number, string>>;

export function GetGitBranch(arg1:string):Promise<string>;

export function GetLayout(arg1:number):Promise<string>;

export function GetProject(arg1:number):Promise<project.Project>;

export function GetWSPort():Promise<number>;

export function ListAgents():Promise<Array<agent.Agent>>;

export function ListProjectAgents(arg1:number):Promise<Array<agent.Agent>>;

export function ListProjectFiles(arg1:string):Promise<Array<string>>;

export function ListProjects():Promise<Array<project.Project>>;

export function ReadDir(arg1:string):Promise<Array<filetree.FileEntry>>;

export function ReadDirFiltered(arg1:string):Promise<Array<filetree.FileEntry>>;

export function ReadFile(arg1:string):Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveLayout(arg1:number,arg2:string):Promise<void>;

export function SpawnAgent(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<agent.SpawnResult>;

export function StopAgent(arg1:string):Promise<void>;

export function UpdateProject(arg1:number,arg2:project.UpdateFields):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
