// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {filetree} from '../models';

export function AddProject(arg1:string,arg2:string):Promise<project.Project>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateTerminal(arg1:string,arg2:number,arg3:number):Promise<string>;

export function DeleteProject(arg1:number):Promise<void>;

export function GetProject(arg1:number):Promise<project.Project>;

export function GetWSPort():Promise<number>;

export function ListProjects():Promise<Array<project.Project>>;

export function ReadDir(arg1:string):Promise<Array<filetree.FileEntry>>;

export function ReadFile(arg1:string):Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
