// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {git} from '../models';
import {agent} from '../models';
import {filetree} from '../models';

export function AbortMerge(arg1:number):Promise<void>;

export function AddProject(arg1:string,arg2:string):Promise<project.Project>;

export function AssignWorktreeAgent(arg1:number,arg2:string):Promise<void>;

export function CleanupWorktree(arg1:number,arg2:string,arg3:boolean):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CommitReviewedChanges(arg1:number,arg2:string,arg3:Array<string>,arg4:boolean):Promise<string>;

export function CompleteMerge(arg1:number):Promise<void>;

export function CreateBranch(arg1:number,arg2:string,arg3:string):Promise<void>;

export function CreateTerminal(arg1:string,arg2:number,arg3:number):Promise<string>;

export function CreateWorktree(arg1:number,arg2:string):Promise<string>;

export function DeleteBranch(arg1:number,arg2:string,arg3:boolean):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function GetAllLayouts():Promise<Record<number, string>>;

export function GetCommitFileChanges(arg1:number,arg2:string):Promise<Array<git.FileChange>>;

export function GetCommitFileDiff(arg1:number,arg2:string,arg3:string):Promise<git.FileDiff>;

export function GetFileDiff(arg1:number,arg2:string,arg3:string,arg4:string):Promise<agent.FileDiff>;

export function GetGitBranch(arg1:string):Promise<string>;

export function GetGitLog(arg1:number,arg2:number,arg3:number):Promise<Array<git.CommitInfo>>;

export function GetGitStatus(arg1:number):Promise<Array<git.FileStatus>>;

export function GetLayout(arg1:number):Promise<string>;

export function GetProject(arg1:number):Promise<project.Project>;

export function GetRunByAgentID(arg1:string):Promise<agent.AgentRunWithStats>;

export function GetRunFileChanges(arg1:number):Promise<Array<agent.RunFileChange>>;

export function GetWSPort():Promise<number>;

export function GetWorkingTreeChanges(arg1:number):Promise<Array<agent.RunFileChange>>;

export function GetWorkingTreeFileDiff(arg1:number,arg2:string):Promise<agent.FileDiff>;

export function HasConflicts(arg1:number):Promise<boolean>;

export function ListAgents():Promise<Array<agent.Agent>>;

export function ListBranches(arg1:number):Promise<Array<git.Branch>>;

export function ListConflictFiles(arg1:number):Promise<Array<string>>;

export function ListProjectAgents(arg1:number):Promise<Array<agent.Agent>>;

export function ListProjectFiles(arg1:string):Promise<Array<string>>;

export function ListProjectRuns(arg1:number):Promise<Array<agent.AgentRunWithStats>>;

export function ListProjects():Promise<Array<project.Project>>;

export function ListWorktrees(arg1:number):Promise<Array<git.Worktree>>;

export function MarkFileResolved(arg1:number,arg2:string):Promise<void>;

export function MergeBranch(arg1:number,arg2:string):Promise<git.MergeResult>;

export function MergeWorktreeBranch(arg1:number,arg2:string):Promise<git.MergeResult>;

export function ReadDir(arg1:string):Promise<Array<filetree.FileEntry>>;

export function ReadDirFiltered(arg1:string):Promise<Array<filetree.FileEntry>>;

export function ReadFile(arg1:string):Promise<string>;

export function RemoveWorktree(arg1:number,arg2:string,arg3:boolean):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RerunAgent(arg1:string):Promise<agent.SpawnResult>;

export function RevertFile(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveLayout(arg1:number,arg2:string):Promise<void>;

export function SpawnAgent(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<agent.SpawnResult>;

export function StashDrop(arg1:number,arg2:number):Promise<void>;

export function StashList(arg1:number):Promise<Array<git.StashEntry>>;

export function StashPop(arg1:number,arg2:number):Promise<void>;

export function StashPush(arg1:number,arg2:string):Promise<void>;

export function StopAgent(arg1:string):Promise<void>;

export function SwitchBranch(arg1:number,arg2:string):Promise<void>;

export function UpdateProject(arg1:number,arg2:project.UpdateFields):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
