// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1, arg2) {
  return window['go']['main']['App']['AddProject'](arg1, arg2);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2, arg3);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetAllLayouts() {
  return window['go']['main']['App']['GetAllLayouts']();
}

export function GetGitBranch(arg1) {
  return window['go']['main']['App']['GetGitBranch'](arg1);
}

export function GetLayout(arg1) {
  return window['go']['main']['App']['GetLayout'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetWSPort() {
  return window['go']['main']['App']['GetWSPort']();
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListProjectAgents(arg1) {
  return window['go']['main']['App']['ListProjectAgents'](arg1);
}

export function ListProjectFiles(arg1) {
  return window['go']['main']['App']['ListProjectFiles'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function ReadDirFiltered(arg1) {
  return window['go']['main']['App']['ReadDirFiltered'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveLayout(arg1, arg2) {
  return window['go']['main']['App']['SaveLayout'](arg1, arg2);
}

export function SpawnAgent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SpawnAgent'](arg1, arg2, arg3, arg4, arg5);
}

export function StopAgent(arg1) {
  return window['go']['main']['App']['StopAgent'](arg1);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
