// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortMerge(arg1) {
  return window['go']['main']['App']['AbortMerge'](arg1);
}

export function AddProject(arg1, arg2) {
  return window['go']['main']['App']['AddProject'](arg1, arg2);
}

export function AssignWorktreeAgent(arg1, arg2) {
  return window['go']['main']['App']['AssignWorktreeAgent'](arg1, arg2);
}

export function CleanupWorktree(arg1, arg2, arg3) {
  return window['go']['main']['App']['CleanupWorktree'](arg1, arg2, arg3);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CommitReviewedChanges(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CommitReviewedChanges'](arg1, arg2, arg3, arg4);
}

export function CompleteMerge(arg1) {
  return window['go']['main']['App']['CompleteMerge'](arg1);
}

export function CreateBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBranch'](arg1, arg2, arg3);
}

export function CreateTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2, arg3);
}

export function CreateWorktree(arg1, arg2) {
  return window['go']['main']['App']['CreateWorktree'](arg1, arg2);
}

export function DeleteBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteBranch'](arg1, arg2, arg3);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetAgentLog(arg1) {
  return window['go']['main']['App']['GetAgentLog'](arg1);
}

export function GetAgentStateHistory(arg1) {
  return window['go']['main']['App']['GetAgentStateHistory'](arg1);
}

export function GetAllLayouts() {
  return window['go']['main']['App']['GetAllLayouts']();
}

export function GetCommitFileChanges(arg1, arg2) {
  return window['go']['main']['App']['GetCommitFileChanges'](arg1, arg2);
}

export function GetCommitFileDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCommitFileDiff'](arg1, arg2, arg3);
}

export function GetFileDiff(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFileDiff'](arg1, arg2, arg3, arg4);
}

export function GetGitBranch(arg1) {
  return window['go']['main']['App']['GetGitBranch'](arg1);
}

export function GetGitLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetGitLog'](arg1, arg2, arg3);
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetLayout(arg1) {
  return window['go']['main']['App']['GetLayout'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetRunByAgentID(arg1) {
  return window['go']['main']['App']['GetRunByAgentID'](arg1);
}

export function GetRunFileChanges(arg1) {
  return window['go']['main']['App']['GetRunFileChanges'](arg1);
}

export function GetWSPort() {
  return window['go']['main']['App']['GetWSPort']();
}

export function GetWorkingTreeChanges(arg1) {
  return window['go']['main']['App']['GetWorkingTreeChanges'](arg1);
}

export function GetWorkingTreeFileDiff(arg1, arg2) {
  return window['go']['main']['App']['GetWorkingTreeFileDiff'](arg1, arg2);
}

export function HasConflicts(arg1) {
  return window['go']['main']['App']['HasConflicts'](arg1);
}

export function ListActivityEvents(arg1, arg2) {
  return window['go']['main']['App']['ListActivityEvents'](arg1, arg2);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListBranches(arg1) {
  return window['go']['main']['App']['ListBranches'](arg1);
}

export function ListConflictFiles(arg1) {
  return window['go']['main']['App']['ListConflictFiles'](arg1);
}

export function ListProjectActivityEvents(arg1, arg2) {
  return window['go']['main']['App']['ListProjectActivityEvents'](arg1, arg2);
}

export function ListProjectAgents(arg1) {
  return window['go']['main']['App']['ListProjectAgents'](arg1);
}

export function ListProjectRuns(arg1) {
  return window['go']['main']['App']['ListProjectRuns'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListWorktrees(arg1) {
  return window['go']['main']['App']['ListWorktrees'](arg1);
}

export function MarkFileResolved(arg1, arg2) {
  return window['go']['main']['App']['MarkFileResolved'](arg1, arg2);
}

export function MergeBranch(arg1, arg2) {
  return window['go']['main']['App']['MergeBranch'](arg1, arg2);
}

export function MergeWorktreeBranch(arg1, arg2) {
  return window['go']['main']['App']['MergeWorktreeBranch'](arg1, arg2);
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function ReadDirFiltered(arg1) {
  return window['go']['main']['App']['ReadDirFiltered'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RemoveWorktree(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveWorktree'](arg1, arg2, arg3);
}

export function RerunAgent(arg1) {
  return window['go']['main']['App']['RerunAgent'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RevertFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RevertFile'](arg1, arg2, arg3, arg4);
}

export function SaveLayout(arg1, arg2) {
  return window['go']['main']['App']['SaveLayout'](arg1, arg2);
}

export function SpawnAgent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SpawnAgent'](arg1, arg2, arg3, arg4, arg5);
}

export function StashDrop(arg1, arg2) {
  return window['go']['main']['App']['StashDrop'](arg1, arg2);
}

export function StashList(arg1) {
  return window['go']['main']['App']['StashList'](arg1);
}

export function StashPop(arg1, arg2) {
  return window['go']['main']['App']['StashPop'](arg1, arg2);
}

export function StashPush(arg1, arg2) {
  return window['go']['main']['App']['StashPush'](arg1, arg2);
}

export function StopAgent(arg1) {
  return window['go']['main']['App']['StopAgent'](arg1);
}

export function SwitchBranch(arg1, arg2) {
  return window['go']['main']['App']['SwitchBranch'](arg1, arg2);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2);
}
